/* eslint-disable @next/next/no-page-custom-font */
import { Header } from "./components/header";
import styles from "../styles/Home.module.scss";
import Head from "next/head";
import Link from 'next/link';
import { Sidebar } from "./components/sidebar";
import { useState, useEffect } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { Autoplay, Pagination, Navigation } from "swiper";
import {ArrowRight} from 'phosphor-react'
//-----------------------------------------------------------------//
export default function Home(props: any) {
  interface dataMovie {
    id:number,
    poster_path:string,
    backdrop_path:string,
    overview:string
    title: string,
    popularity:number,
    release_date: string,
    vote_average:number,
    vote_count:number,
  }
  const [sidebar, setSideBar] = useState(false);
  const [popularMovies, setPopularMovies] = useState([{}]);
  useEffect(() => {
    const GetPopularMovies = async () => {
      const url = "http://localhost:3000/api/movies/popular?type=slide";
      const getMovie = await fetch(url, { next: { revalidate: 10 } });
      const movie = await getMovie.json();
      const results = movie.results;
      results && setPopularMovies(results);
    };
    GetPopularMovies();
  }, []);
  //-------------------------------------------------------------------------------//
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,500;0,700;1,400&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Righteous&family=Roboto:wght@700&display=swap"
          rel="stylesheet"
        />
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Header set={setSideBar} />
      <main className={styles.Main}>
        {sidebar === true && <Sidebar />}
        <div className={styles.NewMovieContainer}>
          <h2 className={styles.textCenterNewMovie}>Filmes Populares</h2>
          <div className={styles.AreaViewMore}>
            <Link href={"/popular"} className={styles.LinkToRedirect}>
              Ver Tudo
              <ArrowRight size={20} weight="bold"/>
            </Link>
            </div>
          <Swiper
            spaceBetween={30}
            centeredSlides={true}
            autoplay={{
              delay: 4500,
              disableOnInteraction: false,
            }}
            pagination={{
              clickable: true,
            }}
            navigation={true}
            modules={[Autoplay, Pagination, Navigation]}
            className={styles.Carrossel}
          >
            {popularMovies.map((item: dataMovie, index) => {
              return (
                <SwiperSlide
                  key={index}
                  className={styles.CarrosselItem}
                  style={{
                    backgroundImage: `url(https://image.tmdb.org/t/p/original${item.backdrop_path})`,
                    backgroundSize: "90%",
                    backgroundPosition: "center",
                    backgroundRepeat: "no-repeat",
                    cursor: "pointer",
                  }}
                  onClick={() => {
                    window.location.href = "/movie";
                  }}
                />
              );
            })}
          </Swiper>
        </div>
      </main>
    </div>
  );
}
